Repository OCA/vertical-association, pull requests merged in 2023-01, with the labels that each got.

#136 [FIX] membership_extension partner categories labels warning
  membership_extension/models/res_partner.py
Labels: bot is merging ⏳, 16.0

#135 [16.0][IMP] membership_extension: Prevent end date before start date on membership_line
  membership_extension/models/membership_line.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#133 [16.0][MIG] membership_variable_period
  membership_variable_period/README.rst
  membership_variable_period/__init__.py
  membership_variable_period/__manifest__.py
  membership_variable_period/i18n/ar.po
  membership_variable_period/i18n/bs.po
  membership_variable_period/i18n/ca.po
  membership_variable_period/i18n/cs.po
  membership_variable_period/i18n/de.po
  membership_variable_period/i18n/en_GB.po
  membership_variable_period/i18n/es.po
  membership_variable_period/i18n/es_CR.po
  membership_variable_period/i18n/es_EC.po
  membership_variable_period/i18n/es_MX.po
  membership_variable_period/i18n/et.po
  membership_variable_period/i18n/fi.po
  membership_variable_period/i18n/fr.po
  membership_variable_period/i18n/fr_CH.po
  membership_variable_period/i18n/hr.po
  membership_variable_period/i18n/hr_HR.po
  membership_variable_period/i18n/hu.po
  membership_variable_period/i18n/it.po
  membership_variable_period/i18n/ja.po
  membership_variable_period/i18n/lt.po
  membership_variable_period/i18n/membership_variable_period.pot
  membership_variable_period/i18n/mk.po
  membership_variable_period/i18n/mn.po
  membership_variable_period/i18n/nb.po
  membership_variable_period/i18n/nl.po
  membership_variable_period/i18n/nl_BE.po
  membership_variable_period/i18n/nl_NL.po
  membership_variable_period/i18n/pt.po
  membership_variable_period/i18n/pt_BR.po
  membership_variable_period/i18n/pt_PT.po
  membership_variable_period/i18n/ro.po
  membership_variable_period/i18n/ru.po
  membership_variable_period/i18n/sl.po
  membership_variable_period/i18n/sv.po
  membership_variable_period/i18n/tr.po
  membership_variable_period/i18n/tr_TR.po
  membership_variable_period/i18n/vi_VN.po
  membership_variable_period/i18n/zh_CN.po
  membership_variable_period/i18n/zh_TW.po
  membership_variable_period/models/__init__.py
  membership_variable_period/models/account_move_line.py
  membership_variable_period/models/product_template.py
  membership_variable_period/readme/CONTRIBUTORS.rst
  membership_variable_period/readme/DESCRIPTION.rst
  membership_variable_period/readme/USAGE.rst
  membership_variable_period/static/description/icon.png
  membership_variable_period/static/description/icon.svg
  membership_variable_period/static/description/icon_main.svg
  membership_variable_period/static/description/index.html
  membership_variable_period/tests/__init__.py
  membership_variable_period/tests/test_membership_variable_period.py
  membership_variable_period/views/product_template_views.xml
  setup/membership_variable_period/odoo/addons/membership_variable_period
  setup/membership_variable_period/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳
