Repository OCA/vertical-association, pull requests merged in 2025-08, with the labels that each got.

#201 [18.0][MIG] membership_variable_period: Migration to 18.0
  membership_variable_period/README.rst
  membership_variable_period/__init__.py
  membership_variable_period/__manifest__.py
  membership_variable_period/i18n/ar.po
  membership_variable_period/i18n/bs.po
  membership_variable_period/i18n/ca.po
  membership_variable_period/i18n/cs.po
  membership_variable_period/i18n/de.po
  membership_variable_period/i18n/en_GB.po
  membership_variable_period/i18n/es.po
  membership_variable_period/i18n/es_CR.po
  membership_variable_period/i18n/es_EC.po
  membership_variable_period/i18n/es_MX.po
  membership_variable_period/i18n/et.po
  membership_variable_period/i18n/fi.po
  membership_variable_period/i18n/fr.po
  membership_variable_period/i18n/fr_CH.po
  membership_variable_period/i18n/hr.po
  membership_variable_period/i18n/hr_HR.po
  membership_variable_period/i18n/hu.po
  membership_variable_period/i18n/it.po
  membership_variable_period/i18n/ja.po
  membership_variable_period/i18n/lt.po
  membership_variable_period/i18n/membership_variable_period.pot
  membership_variable_period/i18n/mk.po
  membership_variable_period/i18n/mn.po
  membership_variable_period/i18n/nb.po
  membership_variable_period/i18n/nl.po
  membership_variable_period/i18n/nl_BE.po
  membership_variable_period/i18n/nl_NL.po
  membership_variable_period/i18n/pt.po
  membership_variable_period/i18n/pt_BR.po
  membership_variable_period/i18n/pt_PT.po
  membership_variable_period/i18n/ro.po
  membership_variable_period/i18n/ru.po
  membership_variable_period/i18n/sl.po
  membership_variable_period/i18n/sv.po
  membership_variable_period/i18n/tr.po
  membership_variable_period/i18n/tr_TR.po
  membership_variable_period/i18n/vi_VN.po
  membership_variable_period/i18n/zh_CN.po
  membership_variable_period/i18n/zh_TW.po
  membership_variable_period/models/__init__.py
  membership_variable_period/models/account_move_line.py
  membership_variable_period/models/product_template.py
  membership_variable_period/pyproject.toml
  membership_variable_period/readme/CONTRIBUTORS.md
  membership_variable_period/readme/DESCRIPTION.md
  membership_variable_period/readme/USAGE.md
  membership_variable_period/static/description/icon.png
  membership_variable_period/static/description/icon.svg
  membership_variable_period/static/description/icon_main.svg
  membership_variable_period/static/description/index.html
  membership_variable_period/tests/__init__.py
  membership_variable_period/tests/test_membership_variable_period.py
  membership_variable_period/views/product_template_views.xml
Labels: approved, migration, ready to merge, bot is merging ⏳

#199 [18.0][MIG] membership_initial_fee: Migration to 18.0
  membership_initial_fee/README.rst
  membership_initial_fee/__init__.py
  membership_initial_fee/__manifest__.py
  membership_initial_fee/i18n/ar.po
  membership_initial_fee/i18n/bs.po
  membership_initial_fee/i18n/ca.po
  membership_initial_fee/i18n/cs.po
  membership_initial_fee/i18n/de.po
  membership_initial_fee/i18n/en_GB.po
  membership_initial_fee/i18n/es.po
  membership_initial_fee/i18n/es_CR.po
  membership_initial_fee/i18n/es_EC.po
  membership_initial_fee/i18n/es_MX.po
  membership_initial_fee/i18n/et.po
  membership_initial_fee/i18n/fi.po
  membership_initial_fee/i18n/fr.po
  membership_initial_fee/i18n/fr_CH.po
  membership_initial_fee/i18n/hr.po
  membership_initial_fee/i18n/hr_HR.po
  membership_initial_fee/i18n/hu.po
  membership_initial_fee/i18n/it.po
  membership_initial_fee/i18n/ja.po
  membership_initial_fee/i18n/lt.po
  membership_initial_fee/i18n/membership_initial_fee.pot
  membership_initial_fee/i18n/mk.po
  membership_initial_fee/i18n/mn.po
  membership_initial_fee/i18n/nb.po
  membership_initial_fee/i18n/nl.po
  membership_initial_fee/i18n/nl_BE.po
  membership_initial_fee/i18n/nl_NL.po
  membership_initial_fee/i18n/pt.po
  membership_initial_fee/i18n/pt_BR.po
  membership_initial_fee/i18n/pt_PT.po
  membership_initial_fee/i18n/ro.po
  membership_initial_fee/i18n/ru.po
  membership_initial_fee/i18n/sl.po
  membership_initial_fee/i18n/sv.po
  membership_initial_fee/i18n/tr.po
  membership_initial_fee/i18n/tr_TR.po
  membership_initial_fee/i18n/vi_VN.po
  membership_initial_fee/i18n/zh_CN.po
  membership_initial_fee/i18n/zh_TW.po
  membership_initial_fee/models/__init__.py
  membership_initial_fee/models/account_move_line.py
  membership_initial_fee/models/product_template.py
  membership_initial_fee/pyproject.toml
  membership_initial_fee/readme/CONTRIBUTORS.md
  membership_initial_fee/readme/DESCRIPTION.md
  membership_initial_fee/readme/ROADMAP.md
  membership_initial_fee/readme/USAGE.md
  membership_initial_fee/static/description/icon.png
  membership_initial_fee/static/description/icon.svg
  membership_initial_fee/static/description/index.html
  membership_initial_fee/tests/__init__.py
  membership_initial_fee/tests/test_membership_initial_fee.py
  membership_initial_fee/views/product_template_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#210 [18.0][MIG] contract_membership_delegated_partner: Migracion to 18.0
  contract_membership_delegated_partner/README.rst
  contract_membership_delegated_partner/__init__.py
  contract_membership_delegated_partner/__manifest__.py
  contract_membership_delegated_partner/i18n/contract_membership_delegated_partner.pot
  contract_membership_delegated_partner/i18n/de.po
  contract_membership_delegated_partner/i18n/es.po
  contract_membership_delegated_partner/i18n/it.po
  contract_membership_delegated_partner/models/__init__.py
  contract_membership_delegated_partner/models/contract.py
  contract_membership_delegated_partner/pyproject.toml
  contract_membership_delegated_partner/readme/CONFIGURE.md
  contract_membership_delegated_partner/readme/CONTRIBUTORS.md
  contract_membership_delegated_partner/readme/DESCRIPTION.md
  contract_membership_delegated_partner/readme/INSTALL.md
  contract_membership_delegated_partner/readme/USAGE.md
  contract_membership_delegated_partner/static/description/icon.png
  contract_membership_delegated_partner/static/description/index.html
  contract_membership_delegated_partner/tests/__init__.py
  contract_membership_delegated_partner/tests/test_delegated_partner_contract.py
  contract_membership_delegated_partner/views/contract.xml
Labels: needs review, approved, migration, bot is merging ⏳

#203 [18.0][MIG] membership_prorate_variable_period: Migration to 18.0
  membership_prorate_variable_period/README.rst
  membership_prorate_variable_period/__init__.py
  membership_prorate_variable_period/__manifest__.py
  membership_prorate_variable_period/i18n/ar.po
  membership_prorate_variable_period/i18n/bs.po
  membership_prorate_variable_period/i18n/ca.po
  membership_prorate_variable_period/i18n/cs.po
  membership_prorate_variable_period/i18n/de.po
  membership_prorate_variable_period/i18n/en_GB.po
  membership_prorate_variable_period/i18n/es.po
  membership_prorate_variable_period/i18n/es_CR.po
  membership_prorate_variable_period/i18n/es_EC.po
  membership_prorate_variable_period/i18n/es_MX.po
  membership_prorate_variable_period/i18n/et.po
  membership_prorate_variable_period/i18n/fi.po
  membership_prorate_variable_period/i18n/fr.po
  membership_prorate_variable_period/i18n/fr_CH.po
  membership_prorate_variable_period/i18n/hr.po
  membership_prorate_variable_period/i18n/hr_HR.po
  membership_prorate_variable_period/i18n/hu.po
  membership_prorate_variable_period/i18n/it.po
  membership_prorate_variable_period/i18n/ja.po
  membership_prorate_variable_period/i18n/lt.po
  membership_prorate_variable_period/i18n/membership_prorate_variable_period.pot
  membership_prorate_variable_period/i18n/mk.po
  membership_prorate_variable_period/i18n/mn.po
  membership_prorate_variable_period/i18n/nb.po
  membership_prorate_variable_period/i18n/nl.po
  membership_prorate_variable_period/i18n/nl_BE.po
  membership_prorate_variable_period/i18n/nl_NL.po
  membership_prorate_variable_period/i18n/pt.po
  membership_prorate_variable_period/i18n/pt_BR.po
  membership_prorate_variable_period/i18n/pt_PT.po
  membership_prorate_variable_period/i18n/ro.po
  membership_prorate_variable_period/i18n/ru.po
  membership_prorate_variable_period/i18n/sl.po
  membership_prorate_variable_period/i18n/sv.po
  membership_prorate_variable_period/i18n/tr.po
  membership_prorate_variable_period/i18n/tr_TR.po
  membership_prorate_variable_period/i18n/vi_VN.po
  membership_prorate_variable_period/i18n/zh_CN.po
  membership_prorate_variable_period/i18n/zh_TW.po
  membership_prorate_variable_period/models/__init__.py
  membership_prorate_variable_period/models/account_move.py
  membership_prorate_variable_period/models/product_template.py
  membership_prorate_variable_period/pyproject.toml
  membership_prorate_variable_period/readme/CONTRIBUTORS.md
  membership_prorate_variable_period/readme/DESCRIPTION.md
  membership_prorate_variable_period/readme/INSTALL.md
  membership_prorate_variable_period/readme/ROADMAP.md
  membership_prorate_variable_period/readme/USAGE.md
  membership_prorate_variable_period/static/description/icon.png
  membership_prorate_variable_period/static/description/icon.svg
  membership_prorate_variable_period/static/description/index.html
  membership_prorate_variable_period/tests/__init__.py
  membership_prorate_variable_period/tests/test_membership_prorate_variable_period.py
Labels: approved, ready to merge, bot is merging ⏳
